steps:
  - task: AzureCLI@2
    displayName: "Create testing dependent resources"
    inputs:
      azureSubscription: "$(SERVICE_PRINCIPAL_NAME)"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        # Add code to create dependencies here if needed.

      useGlobalConfig: true
      failOnStandardError: true
    env: # Make available sensitive secrets from ADO variable group to task
      SAMPLE_SECRET_FROM_VG: $(SAMPLE_SECRET_FROM_VG)